<?php

namespace Nilmanduil\CVBundle\Repository;

/**
 * HobbyCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HobbyCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
