<?php

namespace Nilmanduil\CVBundle\Repository;

/**
 * SkillCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
